# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
