# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsh', '0002_auto_20181116_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_link',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
