# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import urlsh.validators


class Migration(migrations.Migration):

    dependencies = [
        ('urlsh', '0003_auto_20181207_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=300, null=True, validators=[urlsh.validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
