# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsh', '0003_auto_20181118_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_link',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
